# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: szenius/set-timezone@v1.0
    - name: set timezone
      with:
        timezoneLinux: "Asia/Kuala_Lumpur"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test -- --verbose --maxWorkers=1
      env:
        TEST_PHONE: ${{secrets.TEST_PHONE}}
        ADASMS_APPLICATION_SECRET: ${{secrets.ADASMS_APPLICATION_SECRET}}